### ISSUE TITLE
Welcome messages

### ISSUE THREAD

**Issue by xizhao** [fossas/spectrometer#151]
1. install welcome message

After running install:
```
fossamac:~ kevin$ curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9462  100  9462    0     0  21801      0 --:--:-- --:--:-- --:--:-- 21801
fossas/spectrometer info checking GitHub for latest tag
fossas/spectrometer info found version: 2.3.4 for v2.3.4/darwin/amd64
Archive:  fossa_2.3.4_darwin_amd64.zip
  inflating: fossa
fossas/spectrometer info installed /usr/local/bin/fossa
```

It would be really nice to have a welcome message with some color or something letting the user know how to get started.

i.e.

```
Successfully installed fossa-cli!

Visit {docs links} to start get an API key or run `fossa auth`.

When ready, navigate to your repo and run `fossa analyze`.
```

2. Running `fossa` should default to some kind of help or getting started text

3. Errors should have some instructions on how to contact fossa

```
fossamac:fossa-site kevin$ fossa report --json attribution

Using project name: `git@github.com:fossas/fossa-site.git`
Using revision: `956e7113b4d861d979618b90cdde3a3a9c4b09e4`
----------
A fatal error occurred:

    The build failed. Check the FOSSA webapp for more details.


>>>
Relevant warnings include:
```

**Comment by xizhao** [comment]
I know this is a backend change too, but it would be amazing if we could jump in and add a tiny bit of parsing in order to humanize the titles that end up in fossa.

![image](https://user-images.githubusercontent.com/2066021/97754578-fdd59300-1ab4-11eb-99ad-4bb895f7d2ef.png)

**Comment by scruffystuffs** [comment]
@xizhao The title change is doable.  We can parse URLs which have known patterns.  For the meantime, we have the `--title` option as a workaround.

**Comment by meghfossa** [comment]
Added this on internal backlog, closing this for now, as spectrometer code is migrated to fossa-cli repository.
