### ISSUE TITLE
fossa-cli is discovering targets in paths that should be ignored 

### ISSUE THREAD

**Issue by xizhao** [fossas/spectrometer#152]
I'm running fossa-cli in a regular node repo, and these are paths in here that the cli seems to be looking at which IMO should be ignored, like `node_modules`

```
Analyzing npm project at /Users/kevin/Desktop/fossa-site/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/request/node_modules/form-data/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/uri-js/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/envify/node_modules/jstransform/node_modules/base62/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/karma/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/registry-auth-token/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/is-number-like/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/debug-fabulous/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/@zeit/schemas/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/combined-stream/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/bs-recipes/recipes/webpack.preact-hot-loader/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/arg/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/browserify-zlib/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/chardet/
Analyzing yarn project at /Users/kevin/Desktop/fossa-site/node_modules/formidable/
```

I suggest we mirror the current cli behavior, or we log, perhaps at the end of analysis, that we skipped a few directories and have an option that allows us to scan exhaustively.

**Comment by lucacome** [comment]
I see a similar problem:
`Analyzing setuptools project at .../tests/`

but I only want to analyze `gomod` in the root folder. Is there any way to exclude some paths?

**Comment by lucacome** [comment]
Any updates on this?

**Comment by meghfossa** [comment]
> I see a similar problem:
> `Analyzing setuptools project at .../tests/`
> 
> but I only want to analyze `gomod` in the root folder. Is there any way to exclude some paths?

### Approach 1

You can use [target field](https://github.com/fossas/spectrometer/blob/master/docs/reference/fossa_yml.md#targets) of `.fossa.yml` to exclude specific target (or only analyze specific ones) with spectrometer.

```yaml
# .fossa.yml in root directory
# excludes all setuptools targets
version: 3
targets:
  exclude:
    - type: setuptools
```

Or, you can use exclude [path.exclude](https://github.com/fossas/spectrometer/blob/master/docs/reference/fossa_yml.md#pathsexclude) parameter to exclude specific paths from discovery/analysis.

```yaml excludes specific directory from analysis
# .fossa.yml in root directory
# excludes specific directory from analysis
version: 3
paths:
  exclude:
    - test/Python/testdata/
```

I recommend running `fossa list-targets` on root of your project to identify targets and their directories. 

```txt
[ INFO] Found project: setuptools@test/Python/testdata/
[ INFO] Found target: setuptools@test/Python/testdata/
......
```

### Approach 2 - for `fossa analyze`

If your use case is scoped to `analyze` command within cli, there are `--exclude-path` and `--exclude-target` options, which will also accomplish your desired behaviour. 

```txt
fossa analyze ./my-project-dir --exclude-target setuptools
```

**Comment by lucacome** [comment]
Thanks @meghfossa I used both targets and paths exclude and it works!

GitHub Actions run here: https://github.com/nginxinc/kubernetes-ingress/runs/3315788925
![image](https://user-images.githubusercontent.com/603885/129267495-93adb1c8-f74c-4ca5-ab82-39f36cf5b41c.png)

**Comment by meghfossa** [comment]
That's great - glad to be of help!

![](https://media2.giphy.com/media/A7XIMLfuNxv8EZYO2f/giphy.gif)
