### ISSUE TITLE
Techdebt: Replace `addNode` to `deep`

### ISSUE THREAD

**Issue by meghfossa** [fossas/spectrometer#302]
I don't love that we use the term `node` as the public API for this effect, like `addNode` and the `Node` effect handler.  It's called "deep" in core and the graphing module, and `node` doesn't match the existing `direct` and `edge` effects.  I don't think it's a big deal, so there's no need to change it, but if I'm being nitpicky, then this should be called "deep".

BTW, if "deep" is wrong, then the others are wrong as well and we should clean all of it up.  Doing so now would explode this PR AGAIN, and we **absolutely should not do that**.  But a follow-up PR or a tech debt ticket could be good here.

_Originally posted by @scruffystuffs in https://github.com/fossas/spectrometer/pull/300#discussion_r675733063_

**Comment by scruffystuffs** [comment]
Tickets like this should be tracked internally, rather than in the public repo.  Public issues in this repo are for external/open-source users.
