### ISSUE TITLE
docs/differences-from-v1.md fails to mention missing report options

### ISSUE THREAD

**Issue by carlism** [fossas/spectrometer#304]
V1 report -h lists the following:

> COMMANDS:
>     dependencies  Generate dependencies report
>     licenses      Generate licenses report
>     attribution   Generate attribution report

While V2 report -h lists only attribution:

> Available commands:
>  attribution              Generate attribution report

For anyone who has build downstream scripts for incorporating the dependencies report into their shipping product this is an issue.

**Comment by zlav** [comment]
Hi @carlism, we do not currently support identical output to `fossa report dependencies` or `fossa report licenses` in CLI v2. The alternative command is now going to be `fossa report attribution --json` which will output a full Fossa report that can be parsed for whatever information you are interested in.

**Comment by carlism** [comment]
That sounds like an appropriate addition to differences-from-v1.md

**Comment by zlav** [comment]
Agreed, thanks for opening this issue!
